#define START_TASK_PRI 1
#define LED0_TASK_PRI 2
#define LED1_TASK_PRI 3
#define UART_SERVICE_TASK_PRI 4

#define START_TASK_STK 512
#define LED0_TASK_STK 16
#define LED1_TASK_STK 32
#define UART_SERVICE_TASK_STK 256

#define START_TASK_NAME "StartTsk"
#define LED0_TASK_NAME "LED0Tsk"
#define LED1_TASK_NAME "LED1Tsk"
#define UART_SERVICE_TASK_NAME "UARTSrvTsk"