#define START_TASK_PRI 1
#define LED0_TASK_PRI 2
#define LED1_TASK_PRI 3
#define UART_SERVICE_TASK_PRI 4

#define START_TASK_STK 256
#define LED0_TASK_STK 128
#define LED1_TASK_STK 128
#define UART_SERVICE_TASK_STK 128

#define START_TASK_NAME "StartTask"
#define LED0_TASK_NAME "LED0Task"
#define LED1_TASK_NAME "LED1Task"
#define UART_SERVICE_TASK_NAME "UARTServTask"